### Recuperar todas las invitaciones
GET http://localhost:3000/entries
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzg5OWI2ZDczMjZiNjM4NzRkMzdjNyIsInVzZXJuYW1lIjoiYnJhdWxpb2pyIiwiZW1haWwiOiJiYWxvY2hhdmV6bXR6OTlAaG90bWFpbC5jb20iLCJpYXQiOjE2OTkxMTEzODIsImV4cCI6MTY5OTE5Nzc4Mn0.11y88PjMEkT26_PxRodC9lcIDduQ--GeSfhIR9viKIQ

### Recuperar invitacion por id
GET http://localhost:3000/entries/49538452-7b28-11ee-a0b3-84a938a64bb0

### Crear una invitacion
POST http://localhost:3000/entries
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzg5OWI2ZDczMjZiNjM4NzRkMzdjNyIsInVzZXJuYW1lIjoiYnJhdWxpb2pyIiwiZW1haWwiOiJiYWxvY2hhdmV6bXR6OTlAaG90bWFpbC5jb20iLCJpYXQiOjE2OTkxMTEzODIsImV4cCI6MTY5OTE5Nzc4Mn0.11y88PjMEkT26_PxRodC9lcIDduQ--GeSfhIR9viKIQ
Content-Type: application/json

{
  "family": "Familia Rojas Test 3",
  "entriesNumber": 4,
  "phoneNumber": "+528781194465",
  "groupSelected": "Mami",
  "kidsAllowed": true
}

### Actualizar una entrada
PUT http://localhost:3000/entries/49538452-7b28-11ee-a0b3-84a938a64bb0
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1Mzg5OWI2ZDczMjZiNjM4NzRkMzdjNyIsInVzZXJuYW1lIjoiYnJhdWxpb2pyIiwiZW1haWwiOiJiYWxvY2hhdmV6bXR6OTlAaG90bWFpbC5jb20iLCJpYXQiOjE2OTkxMTEzODIsImV4cCI6MTY5OTE5Nzc4Mn0.11y88PjMEkT26_PxRodC9lcIDduQ--GeSfhIR9viKIQ
Content-Type: application/json

{
  "family": "Familia Rojas",
  "entriesNumber": 5,
  "phoneNumber": "+528781194465",
  "groupSelected": "Mami",
  "kidsAllowed": false
}

### Actualizar una entrada confirmada
PATCH http://localhost:3000/entries/49538452-7b28-11ee-a0b3-84a938a64bb0
Content-Type: application/json

{
  "confirmation": true,
  "entriesConfirmed": 4,
  "message": "felicitaciones sofia"
}

### Borrar una invitacion
DELETE http://localhost:3000/entries/b5452fd0-6bde-11ee-bf9e-84a938a64bb0

### Checar signin
POST https://sydney-lyrebird-djqm.1.sg-1.fl0.io/auth/signin
Content-Type: application/json

{
  "username": "brauliojr",
  "email": "bchavez.testing@gmail.com",
  "password": "Pirata99*"
}

### Checar signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "username": "brauliojr",
  "email": "bchavez.testing@gmail.com",
  "password": "p4ssw0rd",
  "roles": ["admin"]
}