### Recuperar todas las invitaciones
GET http://localhost:3000/entries

### Recuperar invitacion por id
GET http://localhost:3000/entries/84ee6113-6b68-11ee-bf9e-84a938a64bb0

### Crear una invitacion
POST http://localhost:3000/entries
Content-Type: application/json

{
  "family": "Familia Rojas",
  "entriesNumber": 4,
  "phoneNumber": "+528781194465",
  "groupSelected": "Mami"
}

### Actualizar una entrada
PUT http://localhost:3000/entries/84ee6113-6b68-11ee-bf9e-84a938a64bb0
Content-Type: application/json

{
  "family": "Familia Rojas",
  "entriesNumber": 5,
  "phoneNumber": "+528781194465",
  "groupSelected": "Mami"
}

### Actualizar una entrada confirmada
PATCH http://localhost:3000/entries/84ee6113-6b68-11ee-bf9e-84a938a64bb0
Content-Type: application/json

{
  "confirmation": true,
  "entriesConfirmed": 4,
  "message": "felicitaciones sofy"
}

### Borrar una invitacion
DELETE http://localhost:3000/entries/84ee6113-6b68-11ee-bf9e-84a938a64bb0